#!/bin/bash

# run the local server. Can be accessed via 127.0.0.1:8080

# yarn build
# RES=$?
# if [[ ${RES} -ne 0 ]]; then
#   exit 1
# fi
#
# docker run --rm -v ./webapp:/usr/share/nginx/html:ro -p 8080:80 nginx

npm start
